id = "neon-pulse-theme"
name = "Neon Pulse Theme"
version = "1.1.0"
schema_version = 1
authors = ["Arnold Rodriguez"]
description = "Colorful theme for Zed editor"
repository = "https://github.com/ArnoldWW/neon-pulse-theme"
